version: 2
updates:
  - package-ecosystem: maven
    directory: /services/java-analyzer
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /services/platform-api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/dashboard
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
