import argparse
import json
import os
import shutil
import stat
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "samples" / "generated" / "week6-auth-removal"
MARKER = ".riskgraph-generated-sample"


FILES = {
    "src/main/java/demo/CustomerRepository.java": """package demo;
interface CustomerRepository { Object findAll(); }
""",
    "src/main/java/demo/CustomerService.java": """package demo;
class CustomerService {
    private CustomerRepository customerRepository;
    Object exportCustomers() { return customerRepository.findAll(); }
}
""",
}

PROTECTED_CONTROLLER = """package demo;
@RestController
@RequestMapping("/admin")
class AdminController {
    private CustomerService customerService;
    @GetMapping("/export")
    @PreAuthorize("hasRole('ADMIN')")
    Object export() { return customerService.exportCustomers(); }
}
"""


def run_git(repository: Path, *arguments: str, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        ["git", *arguments],
        cwd=repository,
        env=env,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result.stdout.strip()


def write(repository: Path, relative_path: str, contents: str) -> None:
    path = repository / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8", newline="\n")


def remove_readonly(function, path: str, _error) -> None:
    os.chmod(path, stat.S_IWRITE)
    function(path)


def create_sample(output: Path) -> dict[str, str]:
    output = output.resolve()
    if output.exists():
        if not (output / MARKER).is_file():
            raise SystemExit(f"Refusing to replace non-sample directory: {output}")
        shutil.rmtree(output, onexc=remove_readonly)
    output.mkdir(parents=True)
    (output / MARKER).write_text("generated by RiskGraph\n", encoding="utf-8", newline="\n")
    run_git(output, "init", "--quiet")
    run_git(output, "config", "user.name", "RiskGraph Sample")
    run_git(output, "config", "user.email", "sample@riskgraph.ai")
    for path, contents in FILES.items():
        write(output, path, contents)
    write(output, "src/main/java/demo/AdminController.java", PROTECTED_CONTROLLER)

    commit_env = os.environ.copy()
    commit_env["GIT_AUTHOR_DATE"] = "2026-01-01T00:00:00Z"
    commit_env["GIT_COMMITTER_DATE"] = "2026-01-01T00:00:00Z"
    run_git(output, "add", ".")
    run_git(output, "commit", "--quiet", "-m", "Protect admin export", env=commit_env)
    old_commit = run_git(output, "rev-parse", "HEAD")

    public_controller = PROTECTED_CONTROLLER.replace(
        "    @PreAuthorize(\"hasRole('ADMIN')\")\n", ""
    )
    write(output, "src/main/java/demo/AdminController.java", public_controller)
    commit_env["GIT_AUTHOR_DATE"] = "2026-01-01T00:01:00Z"
    commit_env["GIT_COMMITTER_DATE"] = "2026-01-01T00:01:00Z"
    run_git(output, "add", ".")
    run_git(output, "commit", "--quiet", "-m", "Remove admin authorization", env=commit_env)
    new_commit = run_git(output, "rev-parse", "HEAD")
    return {
        "repository_path": str(output),
        "old_commit": old_commit,
        "new_commit": new_commit,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create the deterministic Week 6 Spring sample repository"
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(json.dumps(create_sample(args.output), indent=2))


if __name__ == "__main__":
    main()
